### ISSUE TITLE
catalog.ymlに記載のpreface.reが存在しない

### ISSUE THREAD

**Issue by kenhys** [TechBooster/ReVIEW-Template#17]
# 問題点

catalog.ymlには以下のようにpreface.reを指定しているが、リポジトリにはそのようなファイルが存在しない。

```
cat catalog.yml
PREDEF:
  - preface.re

CHAPS:
  - article.re

APPENDIX:

POSTDEF:
  - contributors.re
```

# 期待する状態

articles/preface.reがなにかしらの内容で存在すること。
masterだけでなくTemplate-A5も同じ様子です。

**Comment by kauplan** [comment]
+1

これのせいで、`review-pdfmaker config.yml` がエラーになります（Re:VIEW 2.5の場合）。
