### ISSUE TITLE
Re:VIEW 3.0対応

### ISSUE THREAD

**Issue by takahashim** [TechBooster/ReVIEW-Template#19]
Re:VIEW 3.0では2.0互換機能があるので、このテンプレートも `review_version: 2.0` のままであればビルドできますが、`review_version: 3.0` にするといくつか課題があります。

* ファイル構成が変わったのでそれに合わせる(review-updateコマンドが導入されたのでそれを使えばある程度は自動で対応される)
* layout/layout.tex.erb を原則使わなくなるので、そこの記述の一部を techbooster-doujin.styに移す必要がある
* 通しノンブルのための`\continuenumber`の代替機能が導入されたのでそちらを使うようにする（単純に`\continuenumber`を捨てればOK?）
* ページレイアウトをgeometryを捨てて自前で持つようにしたので、`\setlength{\textheight}`等の指定をやめる（たぶん単純に捨てればOK）
* `\captionsize`, `\captionwidth`を定義しているのでnewcommandを変更する（renewcommandにすればOK？）

**Comment by kmuto** [comment]
この機会に見た目や表現手法を改善したり華美にしてみたりしたいか、あるいは過去との完全な互換性を目指したいのか といったあたりの方針も立ててほしいところ。

**Comment by vvakame** [comment]
話題が動いてない…！
過去との互換性は気にしてないと思われるので、技術書としてデフォルトでいい感じのやつが出て利用者が執筆に専念できればそれでいい…という感じのはず…？

**Comment by kmuto** [comment]
@mhidaka さんからテンプレートは依頼済みということでしたが、要件は決めてあったのかな。

**Comment by vvakame** [comment]
むとーさんからもらったPRをmergeしたので解決かな？
