### ISSUE TITLE
scssファイルのとりあつかい

### ISSUE THREAD

**Issue by kmuto** [TechBooster/ReVIEW-Template#24]
style.scss、style-web.scss、epub_style.scssがありますが、css化する処理はどこかにあるんでしょうか？
node-sassはインストール対象になっているようなのですが。

**Comment by kmuto** [comment]
いやnode-sassは入ってなかったですね

**Comment by vvakame** [comment]
あー…ケアされてなさそうですね…(なんで入ってるんだっけ…

**Comment by mhidaka** [comment]
もともとWebで読めるようにするパブリッシング処理があったはずなんだよね。どこかで機能がデグレしてそのままなんだと思う

**Comment by muojp** [comment]
たまたまCSSをいじりたい気持ちになって本issueに気付いたのでpackage.jsonへnode-sassを追加したり試してたんですが これ含めると(利用頻度が著しく低い割に)結構npm依存関係が膨らむの嫌な感じですね。

before
```
$ du -sm node_modules/
19	node_modules/
```

after
```
$ du -sm node_modules/
37	node_modules/
```

`npm install --no-save node-sass`込みのCSSビルド用shを追加するのが無難かも

**Comment by muojp** [comment]
気持ちが形になりました #38

**Comment by mhidaka** [comment]
特に問題にならなさそう。たぶん時代的にはWeb readingの方向だと思う

**Comment by mhidaka** [comment]
お気持ちが #38 でビルダー追加されてるのでOKOK

ありがとね! @muojp
