### ISSUE TITLE
textttでseqsplitをしている都合でスペースが飛ぶ

### ISSUE THREAD

**Issue by kmuto** [TechBooster/ReVIEW-Template#29]
\reviewtt(実体\texttt)内でseqsplitを仕込んでいるんだけど、スペースが含まれているときに飛んでしまう問題がある（\obeyspacesが効かない）。

C89 Techboosterに鹿野さんが協力されたときに何か裏テクを使ったと思われるような記述があるが…？
http://note.golden-lucky.net/2016/01/tex.html

**Comment by kmuto** [comment]
ref.
https://github.com/kmuto/review/issues/1277

**Comment by mhidaka** [comment]
これ、codeで折返したいとき用ぽいけど、この挙動がバタフライエフェクトで出てるぽいすね

**Comment by kmuto** [comment]
はい。
Re:VIEW側PRのとおりRe:VIEW本体側で入れるつもりではあるんですが、Re:VIEWにとっては緊急リリースレベルではないので3ヶ月後の定期リリース行き。
styコード側で対処は厳しいので、てくぶのほうでどうするかとなると

- そのままにしてドキュメントで注意
- seqsplitをやめる→はみ出しやすくなることに
- スペースを~に置換するreview-ext.rbを提供→リファレンスとしててくぶスタイルが使われている中で危ない手段を提供することになるし次Re:VIEWリリースで不要になるものなので避けたほうが

うーん。

**Comment by mhidaka** [comment]
2.4で作ったやつ確認しましたが

![image](https://user-images.githubusercontent.com/322019/54267765-23024e80-45bd-11e9-8b8f-85ff4af81dbd.png)

これで動いてる？気がしますね。どこかでデグレしてるのかな…

**Comment by kmuto** [comment]
あれ。ちょっと調査してみます…

**Comment by kmuto** [comment]
Re:VIEWではtextttをママで使うのではなくreviewttで包むようにしたんですが、そう包むとobeyspacesが無視されてしまうようです。

```
\documentclass[a5paper,uplatex]{jsarticle}
\makeatletter
\usepackage{seqsplit}
\let\textttorg=\texttt
\def\texttt{\begingroup\obeyspaces\do@texttt}
\def\do@texttt#1{\textttorg{\seqsplit{#1\relax}}\endgroup}
\DeclareRobustCommand{\reviewtt}[1]{\texttt{#1}}
%\newcommand{\reviewtt}[1]{\do@texttt{#1}}


\begin{document}
% textttを使う限りは空白は保持
% しかし書き換えたtextttはrobustではなく見出しに入れられない
%\section{\texttt{hello world}}
\texttt{hello world}

% reviewttで包むとスペースが無視される
\section{\reviewtt{hello world}}
\reviewtt{hello world}

\end{document}
```

`\let\reviewtt=\textt`とすると動きはしますがsection等で使えません。

**Comment by k16shikano** [comment]
最初の定義では、スペースをつぶさないために` `\obeyspaces` を使っています。これは空白文字のcatcodeを書き換えるのですが、その書き換えの効果をもたらすためには展開のタイミングをずらす必要があって、そのために `\do@texttt` というマクロを一段かませていました。

その後、Re:VIEWの方針が変わって `@<tt>` を生の `\texttt` ではなく `\reviewtt` という独立したコマンドにマッピングするようになったようですが（ https://github.com/kmuto/review/commit/e758b293c821255e2ffd83d7afed7a27a36281b0 ）、このときにデフォルトの `\reviett` の定義が次のようになったことが、本文でスペースがつぶれるようになってしまった原因です。

```tex
\newcommand{\reviewtt}[1]{\texttt{#1}}
```

`\newcommand` は、 `[]` を明示してコマンドAを定義すると、実際にそのコマンドAが内部で `\def` される前に引数をトークンリストに置いてしまうので、`\obeyspaces` が間に合いません。もし `\newcommand{\reviewtt}{\texttt}` と定義されていたなら、`\texttt` が利用される段階になってはじめて引数を見に行くので、`\obeyspaces` が間に合って以前と同じ挙動になります。

`\DeclareRobustCommand` も、内部で `\newcommand` と同じ処理に行くつくので、引数を `[]` で指定すると同じ結果になります。以下のような宣言なら、`\protect` されたバージョンの `\texttt` が用意されるだけなので、以前と同じ挙動になっていました。

```tex
\DeclareRobustCommand{\reviewtt}{\texttt}
```

ここまでが、なぜ `\reviewtt` の導入によって `seqsplit` で `\obeyspaces` が効かなくなったか、です。

これとは別の話として、`\section` とかでエラーが起きたり、スペースがつぶれたりする現象がありますが、これは要するに `seqsplit` が完全展開しないからで、したがってこのパッケージを使う限りはきれいな解決策はないと思います。

Re:VIEW側で必要になる対処は、こんな感じに思えます。

* 「デフォルトの挙動を安全にしておく」ための対応として次の2つのうちいずれか。
    * `\reviewtt` のデフォルトの定義を上のように `\DeclareRobustCommand` する
    * `@<tt>` に対するlatexbuilderの出力を `\protect\reviewtt` にする
       * ただしいずれもスペースを保持するためには`\noexpand`や下記のサポートが必要になる

* 「ユーザが `\reviewtt` を再定義しやすくする」ための対応として次の2つのうちいずれか
    * 空白を`~`に変換する
    * 空白を `\ ` でエスケープする

てくぶスタイルで必要な処理としては、`\texttt` を書き換える必要がなくなったので `\reviewtt` を書き換えるようにしつつ、デフォルトはコメントアウトするなりして使わせない（使うなら自己責任で）とするのがいいのではないでしょうか。

**Comment by kmuto** [comment]
@munepi さんからの提案実装
- https://gist.github.com/munepi/a9d1205aa166456cb0037402fda9ecf9

**Comment by k16shikano** [comment]
これは文字とスペースの間でないと改行してくれない気がします。（もともと欲しかったのは文字が連続しても改行してくれる仕掛け）

**Comment by kmuto** [comment]
なるほど…

ひとまずRe:VIEW本体のほうは

- kmuto/review#1278
- kmuto/review#1280

を次のバージョンで入れようかと思っています。あとはてくぶスタイルのほうはそれまでの間どうするかですね…。次のRe:VIEWバージョンで不整合になるものは作りたくないところです。

**Comment by k16shikano** [comment]
もともと`\texttt`を書き換えるしか手がなかったことに課題があり、それは`\reviewtt`の導入で解消されたわけですから、まず `articles/sty/techbooster-doujin-base.sty` をこう修正するのがいいと思います。（試してません）

```diff
@@ -49,16 +49,11 @@
 \usepackage{fancyvrb}
 \VerbatimFootnotes

-% ttでの折り返しの許容
-\usepackage{seqsplit}
-\let\textttorg=\texttt
-\def\texttt{\begingroup\obeyspaces\do@texttt}
-\def\do@texttt#1{\textttorg{\seqsplit{#1\relax}}\endgroup}
-% 目次に入る可能性があるのでRobust化しておく
-\DeclareRobustCommand{\reviewtt}[1]{\texttt{#1}}
-\DeclareRobustCommand{\reviewcode}[1]{\texttt{#1}}
-\DeclareRobustCommand{\reviewtti}[1]{\texttt{\textit{#1}}}
-\DeclareRobustCommand{\reviewttb}[1]{\texttt{\textbf{#1}}}
+%% @<tt>内の任意の位置で折り返しを許容したい場合には有効化する
+%% 見出しに@<tt>がある場合には使わないこと（必要に応じて\protectや\noexpandが必要（意味がわからない場合には使わない
+%\usepackage{seqsplit}
+%\def\reviewtt{\begingroup\obeyspaces\do@texttt}
+%\def\do@texttt#1{\textttorg{\seqsplit{#1\relax}}\endgroup}

 \renewcommand{\captionsize}{\fontsize{9}{9}\selectfont}
 \newlength{\captionnumwidth}
```

`@<tt>`の挙動を変えるのに`\texttt`を触るしか手がなかったところで私がkludgeを仕込み、それが本家が提供するLaTeXスタイルとは別に（もしかしたら本家よりも）広く使われる状況になったことで困難が生まれたと思うので（LaTeXのスタイルはCSSのようには変換器の振る舞いから独立して切り替えられない）、`\reviewtt`が導入されたいま、てくぶスタイルでも標準の動作に戻すのをデフォルトにするのがいいと思います。

**Comment by kmuto** [comment]
#35 でデフォルトを無効に倒す設定にしてみました。
styに書いても誰も読んでくれないだろうか…

**Comment by kmuto** [comment]
なんかスゴイのキタ。
ざっと試したところでかなりいい感じがします。こっち側の実装にしてみようかと

- https://gist.github.com/zr-tex8r/69c506626c4a8545ff4c95482cb55add

**Comment by kmuto** [comment]
#36 で実装しました。#35 は破棄、#36 採用 がよさそうな感じではありますが、いちおう @mhidaka さんのほうでもテストいただけます？

**Comment by mhidaka** [comment]
👀 ほい。みてみます
