### ISSUE TITLE
改ページでノンブルが消失している

### ISSUE THREAD

**Issue by mhidaka** [TechBooster/ReVIEW-Template#30]
目次が左半分でおわったときなどのこりの右ページのノンブルがきえてて通しノンブルが打ててない問題がある（これ前はなかったと思うのでエンバグしてしまっている気がする…）

直し方わかりますか？ @kmuto

**Comment by kmuto** [comment]
む、調査します。

**Comment by kmuto** [comment]
今のてくぶのconfig.ymlではtexdocumentclassにhiddenfolio=nikko-pcパラメータを付けるようにしていて、ノドに通しノンブルは入ってるはずですが、これだと嫌、ということでしょうか。

clearpageのところをいじれば実装自体はできそうですが。

**Comment by kmuto** [comment]
あ、目次だけなんか変ですね。

**Comment by kmuto** [comment]
#31 に修正提案をPRしてみます。
