### ISSUE TITLE
tableフロートもH(強制here)にする？

### ISSUE THREAD

**Issue by kmuto** [TechBooster/ReVIEW-Template#32]
今のreview-style.styは後方互換性のために図・表のfloatは
```
\floatplacement{figure}{H} ←必ずそこに置く
\floatplacement{table}{htp} ←そこに置けなかったらフロートしてtopか新ページ
```
と設定しています。てくぶの場合は別にこれにひきずられる必要もないので、techbooster-doujin-base.styのほうで上書きして両方ともHにしたほうが、直感的な結果にはなりそうです（フロートは扱いがなかなか難しい）。

**Comment by mhidaka** [comment]
```
H：絶対に指定箇所に置く（float.sty の効果）
h：できれば指定箇所に置く。少しでも無理ならあきらめて次の候補へ
t：版面上端に置く
b：版面下端に置く
p：単独のページに置く
```
https://review-knowledge-ja.readthedocs.io/ja/latest/latex/control-flow.html
このあたりの指定の話っぽいですね。
うけたまわりです
